const billingData = {
    "target": 820,
    "dailyTarget": 41,
    "team": [
        {
            "id": 1,
            "name": "Abigail",
            "profileImg": "https://images.unsplash.com/photo-1554151228-14d9def656e4?w=400"
        },
        {
            "id": 2,
            "name": "Carlos",
            "profileImg": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400"
        },
        {
            "id": 3,
            "name": "Daniela",
            "profileImg": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400"
        },
        {
            "id": 4,
            "name": "Eduardo",
            "profileImg": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400"
        },
        {
            "id": 5,
            "name": "Fernanda",
            "profileImg": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400"
        },
        {
            "id": 6,
            "name": "Gabriel",
            "profileImg": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400"
        },
        {
            "id": 7,
            "name": "Hilda",
            "profileImg": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400"
        }
    ],
    "monthlyData": {
        "1": [
            {
                "month": "January",
                "actual": 800,
                "jobsActual": 234,
                "target": 0,
                "b31_60": 5,
                "b61_90": 5,
                "b90": 5,
                "quality": 100,
                "issues": 10,
                "holidays": 0,
                "workingDays": 20
            },
            {
                "month": "February",
                "actual": 800,
                "jobsActual": 417,
                "target": 0,
                "b31_60": 5,
                "b61_90": 5,
                "b90": 5,
                "quality": 100,
                "issues": 10,
                "holidays": 0,
                "workingDays": 20
            },
            {
                "month": "March",
                "actual": 358,
                "jobsActual": 358,
                "target": 0,
                "b31_60": 30,
                "b61_90": 0,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "April",
                "actual": 336,
                "jobsActual": 336,
                "target": 0,
                "b31_60": 30,
                "b61_90": 5,
                "b90": 2,
                "quality": 100,
                "issues": 1,
                "holidays": 4,
                "workingDays": 16
            },
            {
                "month": "May",
                "actual": 269,
                "jobsActual": 269,
                "target": 0,
                "b31_60": 15,
                "b61_90": 1,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 0,
                "workingDays": 20
            },
            {
                "month": "June",
                "actual": 304,
                "jobsActual": 304,
                "target": 0,
                "b31_60": 19,
                "b61_90": 1,
                "b90": 0,
                "quality": 100,
                "issues": 3,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "July",
                "actual": 364,
                "jobsActual": 364,
                "target": 0,
                "b31_60": 62,
                "b61_90": 1,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 0,
                "workingDays": 20
            },
            {
                "month": "August",
                "actual": 341,
                "jobsActual": 341,
                "target": 0,
                "b31_60": 30,
                "b61_90": 1,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 2,
                "workingDays": 18
            },
            {
                "month": "September",
                "actual": 465,
                "jobsActual": 465,
                "target": 0,
                "b31_60": 108,
                "b61_90": 39,
                "b90": 13,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "October",
                "actual": 604,
                "jobsActual": 604,
                "target": 0,
                "b31_60": 152,
                "b61_90": 51,
                "b90": 31,
                "quality": 100,
                "issues": 0,
                "holidays": 2,
                "workingDays": 18
            },
            {
                "month": "November",
                "actual": 487,
                "jobsActual": 487,
                "target": 0,
                "b31_60": 106,
                "b61_90": 29,
                "b90": 9,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "December",
                "actual": 628,
                "jobsActual": 628,
                "target": 0,
                "b31_60": 80,
                "b61_90": 20,
                "b90": 5,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            }
        ],
        "2": [
            {
                "month": "January",
                "actual": 541,
                "jobsActual": 541,
                "target": 0,
                "b31_60": 11,
                "b61_90": 0,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "February",
                "actual": 489,
                "jobsActual": 453,
                "target": 0,
                "b31_60": 18,
                "b61_90": 1,
                "b90": 0,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "March",
                "actual": 771,
                "jobsActual": 218,
                "target": 0,
                "b31_60": 0,
                "b61_90": 7,
                "b90": 0,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "April",
                "actual": 352,
                "jobsActual": 760,
                "target": 0,
                "b31_60": 18,
                "b61_90": 0,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "May",
                "actual": 586,
                "jobsActual": 787,
                "target": 0,
                "b31_60": 45,
                "b61_90": 1,
                "b90": 2,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "June",
                "actual": 246,
                "jobsActual": 764,
                "target": 0,
                "b31_60": 46,
                "b61_90": 7,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "July",
                "actual": 704,
                "jobsActual": 769,
                "target": 0,
                "b31_60": 41,
                "b61_90": 8,
                "b90": 4,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "August",
                "actual": 654,
                "jobsActual": 310,
                "target": 0,
                "b31_60": 43,
                "b61_90": 1,
                "b90": 3,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "September",
                "actual": 189,
                "jobsActual": 729,
                "target": 0,
                "b31_60": 8,
                "b61_90": 0,
                "b90": 1,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "October",
                "actual": 751,
                "jobsActual": 248,
                "target": 0,
                "b31_60": 25,
                "b61_90": 9,
                "b90": 4,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "November",
                "actual": 237,
                "jobsActual": 48,
                "target": 0,
                "b31_60": 29,
                "b61_90": 5,
                "b90": 3,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "December",
                "actual": 540,
                "jobsActual": 767,
                "target": 0,
                "b31_60": 8,
                "b61_90": 3,
                "b90": 1,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            }
        ],
        "3": [
            {
                "month": "January",
                "actual": 468,
                "jobsActual": 586,
                "target": 0,
                "b31_60": 36,
                "b61_90": 5,
                "b90": 2,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "February",
                "actual": 690,
                "jobsActual": 82,
                "target": 0,
                "b31_60": 40,
                "b61_90": 8,
                "b90": 3,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "March",
                "actual": 677,
                "jobsActual": 427,
                "target": 0,
                "b31_60": 0,
                "b61_90": 1,
                "b90": 2,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "April",
                "actual": 118,
                "jobsActual": 123,
                "target": 0,
                "b31_60": 37,
                "b61_90": 0,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "May",
                "actual": 662,
                "jobsActual": 539,
                "target": 0,
                "b31_60": 30,
                "b61_90": 2,
                "b90": 1,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "June",
                "actual": 136,
                "jobsActual": 74,
                "target": 0,
                "b31_60": 38,
                "b61_90": 9,
                "b90": 2,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "July",
                "actual": 244,
                "jobsActual": 642,
                "target": 0,
                "b31_60": 24,
                "b61_90": 9,
                "b90": 4,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "August",
                "actual": 59,
                "jobsActual": 192,
                "target": 0,
                "b31_60": 1,
                "b61_90": 2,
                "b90": 3,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "September",
                "actual": 463,
                "jobsActual": 463,
                "target": 0,
                "b31_60": 32,
                "b61_90": 3,
                "b90": 2,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "October",
                "actual": 24,
                "jobsActual": 387,
                "target": 0,
                "b31_60": 46,
                "b61_90": 4,
                "b90": 4,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "November",
                "actual": 182,
                "jobsActual": 260,
                "target": 0,
                "b31_60": 38,
                "b61_90": 1,
                "b90": 3,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "December",
                "actual": 547,
                "jobsActual": 20,
                "target": 0,
                "b31_60": 42,
                "b61_90": 2,
                "b90": 1,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            }
        ],
        "4": [
            {
                "month": "January",
                "actual": 450,
                "jobsActual": 622,
                "target": 0,
                "b31_60": 7,
                "b61_90": 4,
                "b90": 3,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "February",
                "actual": 58,
                "jobsActual": 155,
                "target": 0,
                "b31_60": 12,
                "b61_90": 7,
                "b90": 3,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "March",
                "actual": 373,
                "jobsActual": 300,
                "target": 0,
                "b31_60": 33,
                "b61_90": 6,
                "b90": 4,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "April",
                "actual": 283,
                "jobsActual": 103,
                "target": 0,
                "b31_60": 0,
                "b61_90": 4,
                "b90": 3,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "May",
                "actual": 18,
                "jobsActual": 465,
                "target": 0,
                "b31_60": 9,
                "b61_90": 4,
                "b90": 1,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "June",
                "actual": 748,
                "jobsActual": 769,
                "target": 0,
                "b31_60": 8,
                "b61_90": 0,
                "b90": 4,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "July",
                "actual": 434,
                "jobsActual": 542,
                "target": 0,
                "b31_60": 46,
                "b61_90": 3,
                "b90": 3,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "August",
                "actual": 106,
                "jobsActual": 679,
                "target": 0,
                "b31_60": 19,
                "b61_90": 7,
                "b90": 2,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "September",
                "actual": 783,
                "jobsActual": 76,
                "target": 0,
                "b31_60": 17,
                "b61_90": 7,
                "b90": 4,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "October",
                "actual": 60,
                "jobsActual": 164,
                "target": 0,
                "b31_60": 20,
                "b61_90": 1,
                "b90": 3,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "November",
                "actual": 471,
                "jobsActual": 787,
                "target": 0,
                "b31_60": 8,
                "b61_90": 6,
                "b90": 0,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "December",
                "actual": 130,
                "jobsActual": 544,
                "target": 0,
                "b31_60": 33,
                "b61_90": 0,
                "b90": 3,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            }
        ],
        "5": [
            {
                "month": "January",
                "actual": 237,
                "jobsActual": 529,
                "target": 0,
                "b31_60": 13,
                "b61_90": 0,
                "b90": 4,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "February",
                "actual": 128,
                "jobsActual": 546,
                "target": 0,
                "b31_60": 3,
                "b61_90": 7,
                "b90": 3,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "March",
                "actual": 760,
                "jobsActual": 29,
                "target": 0,
                "b31_60": 39,
                "b61_90": 0,
                "b90": 2,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "April",
                "actual": 586,
                "jobsActual": 479,
                "target": 0,
                "b31_60": 40,
                "b61_90": 6,
                "b90": 3,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "May",
                "actual": 602,
                "jobsActual": 249,
                "target": 0,
                "b31_60": 45,
                "b61_90": 5,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "June",
                "actual": 626,
                "jobsActual": 358,
                "target": 0,
                "b31_60": 2,
                "b61_90": 3,
                "b90": 1,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "July",
                "actual": 621,
                "jobsActual": 593,
                "target": 0,
                "b31_60": 43,
                "b61_90": 5,
                "b90": 2,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "August",
                "actual": 571,
                "jobsActual": 640,
                "target": 0,
                "b31_60": 42,
                "b61_90": 8,
                "b90": 4,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "September",
                "actual": 548,
                "jobsActual": 521,
                "target": 0,
                "b31_60": 40,
                "b61_90": 6,
                "b90": 2,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "October",
                "actual": 39,
                "jobsActual": 152,
                "target": 0,
                "b31_60": 14,
                "b61_90": 7,
                "b90": 3,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "November",
                "actual": 246,
                "jobsActual": 731,
                "target": 0,
                "b31_60": 19,
                "b61_90": 1,
                "b90": 0,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "December",
                "actual": 769,
                "jobsActual": 389,
                "target": 0,
                "b31_60": 45,
                "b61_90": 8,
                "b90": 2,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            }
        ],
        "6": [
            {
                "month": "January",
                "actual": 136,
                "jobsActual": 662,
                "target": 0,
                "b31_60": 43,
                "b61_90": 9,
                "b90": 2,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "February",
                "actual": 421,
                "jobsActual": 510,
                "target": 0,
                "b31_60": 36,
                "b61_90": 1,
                "b90": 0,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "March",
                "actual": 246,
                "jobsActual": 145,
                "target": 0,
                "b31_60": 15,
                "b61_90": 4,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "April",
                "actual": 778,
                "jobsActual": 457,
                "target": 0,
                "b31_60": 18,
                "b61_90": 4,
                "b90": 1,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "May",
                "actual": 596,
                "jobsActual": 724,
                "target": 0,
                "b31_60": 5,
                "b61_90": 9,
                "b90": 3,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "June",
                "actual": 35,
                "jobsActual": 396,
                "target": 0,
                "b31_60": 2,
                "b61_90": 7,
                "b90": 4,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "July",
                "actual": 18,
                "jobsActual": 643,
                "target": 0,
                "b31_60": 7,
                "b61_90": 9,
                "b90": 0,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "August",
                "actual": 159,
                "jobsActual": 301,
                "target": 0,
                "b31_60": 21,
                "b61_90": 6,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "September",
                "actual": 483,
                "jobsActual": 691,
                "target": 0,
                "b31_60": 14,
                "b61_90": 8,
                "b90": 3,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "October",
                "actual": 217,
                "jobsActual": 489,
                "target": 0,
                "b31_60": 18,
                "b61_90": 4,
                "b90": 4,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "November",
                "actual": 636,
                "jobsActual": 149,
                "target": 0,
                "b31_60": 13,
                "b61_90": 3,
                "b90": 1,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "December",
                "actual": 62,
                "jobsActual": 625,
                "target": 0,
                "b31_60": 29,
                "b61_90": 7,
                "b90": 3,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            }
        ],
        "7": [
            {
                "month": "January",
                "actual": 227,
                "jobsActual": 377,
                "target": 0,
                "b31_60": 11,
                "b61_90": 8,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "February",
                "actual": 204,
                "jobsActual": 668,
                "target": 0,
                "b31_60": 5,
                "b61_90": 0,
                "b90": 3,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "March",
                "actual": 197,
                "jobsActual": 587,
                "target": 0,
                "b31_60": 8,
                "b61_90": 2,
                "b90": 0,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "April",
                "actual": 757,
                "jobsActual": 219,
                "target": 0,
                "b31_60": 27,
                "b61_90": 9,
                "b90": 1,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "May",
                "actual": 726,
                "jobsActual": 364,
                "target": 0,
                "b31_60": 20,
                "b61_90": 9,
                "b90": 4,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "June",
                "actual": 414,
                "jobsActual": 718,
                "target": 0,
                "b31_60": 4,
                "b61_90": 5,
                "b90": 4,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "July",
                "actual": 348,
                "jobsActual": 478,
                "target": 0,
                "b31_60": 21,
                "b61_90": 6,
                "b90": 2,
                "quality": 100,
                "issues": 0,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "August",
                "actual": 380,
                "jobsActual": 559,
                "target": 0,
                "b31_60": 5,
                "b61_90": 6,
                "b90": 0,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "September",
                "actual": 196,
                "jobsActual": 311,
                "target": 0,
                "b31_60": 24,
                "b61_90": 0,
                "b90": 0,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "October",
                "actual": 108,
                "jobsActual": 67,
                "target": 0,
                "b31_60": 30,
                "b61_90": 2,
                "b90": 3,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "November",
                "actual": 103,
                "jobsActual": 574,
                "target": 0,
                "b31_60": 43,
                "b61_90": 9,
                "b90": 2,
                "quality": 100,
                "issues": 1,
                "holidays": 1,
                "workingDays": 19
            },
            {
                "month": "December",
                "actual": 621,
                "jobsActual": 490,
                "target": 0,
                "b31_60": 46,
                "b61_90": 7,
                "b90": 3,
                "quality": 100,
                "issues": 2,
                "holidays": 1,
                "workingDays": 19
            }
        ]
    }
};

if (typeof module !== 'undefined') {
    module.exports = billingData;
}